version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/factoche:cached
    command: sleep infinity
    env_file:
      - ../.env
    networks:
      - development
    depends_on:
      - db

  db:
    image: postgres:15.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factoche_development
    networks:
      - development

volumes:
  postgres-data:

networks:
  development:
    driver: bridge
