/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthenticatedCompaniesCompanyIdImport } from './routes/_authenticated/companies/$companyId'
import { Route as AuthenticatedCompaniesCompanyIdIndexImport } from './routes/_authenticated/companies/$companyId/index'
import { Route as AuthenticatedCompaniesCompanyIdProjectsIndexImport } from './routes/_authenticated/companies/$companyId/projects/index'
import { Route as AuthenticatedCompaniesCompanyIdClientsIndexImport } from './routes/_authenticated/companies/$companyId/clients/index'
import { Route as AuthenticatedCompaniesCompanyIdProjectsNewImport } from './routes/_authenticated/companies/$companyId/projects/new'
import { Route as AuthenticatedCompaniesCompanyIdClientsNewImport } from './routes/_authenticated/companies/$companyId/clients/new'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/index'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/invoices/new'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/index'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/index'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
import { Route as AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditImport } from './routes/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdIndexRoute =
  AuthenticatedCompaniesCompanyIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdProjectsIndexRoute =
  AuthenticatedCompaniesCompanyIdProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdClientsIndexRoute =
  AuthenticatedCompaniesCompanyIdClientsIndexImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdProjectsNewRoute =
  AuthenticatedCompaniesCompanyIdProjectsNewImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdClientsNewRoute =
  AuthenticatedCompaniesCompanyIdClientsNewImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewImport.update({
    id: '/projects/$projectId/invoices/new',
    path: '/projects/$projectId/invoices/new',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

const AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewImport.update(
    {
      id: '/projects/$projectId/completion_snapshots/new',
      path: '/projects/$projectId/completion_snapshots/new',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

const AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexImport.update(
    {
      id: '/projects/$projectId/invoices/$invoiceId/',
      path: '/projects/$projectId/invoices/$invoiceId/',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

const AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexImport.update(
    {
      id: '/projects/$projectId/completion_snapshots/$completionSnapshotId/',
      path: '/projects/$projectId/completion_snapshots/$completionSnapshotId/',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

const AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewImport.update(
    {
      id: '/projects/$projectId/invoices/completion_snapshots/new',
      path: '/projects/$projectId/invoices/completion_snapshots/new',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

const AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateImport.update(
    {
      id: '/projects/$projectId/invoices/$invoiceId/update',
      path: '/projects/$projectId/invoices/$invoiceId/update',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

const AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute =
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditImport.update(
    {
      id: '/projects/$projectId/completion_snapshots/$completionSnapshotId/edit',
      path: '/projects/$projectId/completion_snapshots/$completionSnapshotId/edit',
      getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/companies/$companyId/': {
      id: '/_authenticated/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/clients/new': {
      id: '/_authenticated/companies/$companyId/clients/new'
      path: '/clients/new'
      fullPath: '/companies/$companyId/clients/new'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdClientsNewImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/new': {
      id: '/_authenticated/companies/$companyId/projects/new'
      path: '/projects/new'
      fullPath: '/companies/$companyId/projects/new'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsNewImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/clients/': {
      id: '/_authenticated/companies/$companyId/clients/'
      path: '/clients'
      fullPath: '/companies/$companyId/clients'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdClientsIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/': {
      id: '/_authenticated/companies/$companyId/projects/'
      path: '/projects'
      fullPath: '/companies/$companyId/projects'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/companies/$companyId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new'
      path: '/projects/$projectId/completion_snapshots/new'
      fullPath: '/companies/$companyId/projects/$projectId/completion_snapshots/new'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/invoices/new': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/invoices/new'
      path: '/projects/$projectId/invoices/new'
      fullPath: '/companies/$companyId/projects/$projectId/invoices/new'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
      path: '/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
      fullPath: '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
      path: '/projects/$projectId/invoices/$invoiceId/update'
      fullPath: '/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
      path: '/projects/$projectId/invoices/completion_snapshots/new'
      fullPath: '/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/'
      path: '/projects/$projectId/completion_snapshots/$completionSnapshotId'
      fullPath: '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
    '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/': {
      id: '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/'
      path: '/projects/$projectId/invoices/$invoiceId'
      fullPath: '/companies/$companyId/projects/$projectId/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedCompaniesCompanyIdRouteChildren {
  AuthenticatedCompaniesCompanyIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdIndexRoute
  AuthenticatedCompaniesCompanyIdClientsNewRoute: typeof AuthenticatedCompaniesCompanyIdClientsNewRoute
  AuthenticatedCompaniesCompanyIdProjectsNewRoute: typeof AuthenticatedCompaniesCompanyIdProjectsNewRoute
  AuthenticatedCompaniesCompanyIdClientsIndexRoute: typeof AuthenticatedCompaniesCompanyIdClientsIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsIndexRoute: typeof AuthenticatedCompaniesCompanyIdProjectsIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute
}

const AuthenticatedCompaniesCompanyIdRouteChildren: AuthenticatedCompaniesCompanyIdRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdIndexRoute:
      AuthenticatedCompaniesCompanyIdIndexRoute,
    AuthenticatedCompaniesCompanyIdClientsNewRoute:
      AuthenticatedCompaniesCompanyIdClientsNewRoute,
    AuthenticatedCompaniesCompanyIdProjectsNewRoute:
      AuthenticatedCompaniesCompanyIdProjectsNewRoute,
    AuthenticatedCompaniesCompanyIdClientsIndexRoute:
      AuthenticatedCompaniesCompanyIdClientsIndexRoute,
    AuthenticatedCompaniesCompanyIdProjectsIndexRoute:
      AuthenticatedCompaniesCompanyIdProjectsIndexRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute,
    AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute:
      AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute,
  }

const AuthenticatedCompaniesCompanyIdRouteWithChildren =
  AuthenticatedCompaniesCompanyIdRoute._addFileChildren(
    AuthenticatedCompaniesCompanyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompaniesCompanyIdRoute:
    AuthenticatedCompaniesCompanyIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
  '/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/companies/$companyId/clients/new': typeof AuthenticatedCompaniesCompanyIdClientsNewRoute
  '/companies/$companyId/projects/new': typeof AuthenticatedCompaniesCompanyIdProjectsNewRoute
  '/companies/$companyId/clients': typeof AuthenticatedCompaniesCompanyIdClientsIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsIndexRoute
  '/companies/$companyId/projects/$projectId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute
  '/companies/$companyId/projects/$projectId/invoices/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute
  '/companies/$companyId/projects/$projectId/invoices/$invoiceId/update': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute
  '/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute
  '/companies/$companyId/projects/$projectId/invoices/$invoiceId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute
}

export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/companies/$companyId/clients/new': typeof AuthenticatedCompaniesCompanyIdClientsNewRoute
  '/companies/$companyId/projects/new': typeof AuthenticatedCompaniesCompanyIdProjectsNewRoute
  '/companies/$companyId/clients': typeof AuthenticatedCompaniesCompanyIdClientsIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsIndexRoute
  '/companies/$companyId/projects/$projectId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute
  '/companies/$companyId/projects/$projectId/invoices/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute
  '/companies/$companyId/projects/$projectId/invoices/$invoiceId/update': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute
  '/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute
  '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute
  '/companies/$companyId/projects/$projectId/invoices/$invoiceId': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
  '/_authenticated/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/_authenticated/companies/$companyId/clients/new': typeof AuthenticatedCompaniesCompanyIdClientsNewRoute
  '/_authenticated/companies/$companyId/projects/new': typeof AuthenticatedCompaniesCompanyIdProjectsNewRoute
  '/_authenticated/companies/$companyId/clients/': typeof AuthenticatedCompaniesCompanyIdClientsIndexRoute
  '/_authenticated/companies/$companyId/projects/': typeof AuthenticatedCompaniesCompanyIdProjectsIndexRoute
  '/_authenticated/companies/$companyId/projects/$projectId/': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdIndexRoute
  '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsNewRoute
  '/_authenticated/companies/$companyId/projects/$projectId/invoices/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesNewRoute
  '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdEditRoute
  '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdUpdateRoute
  '/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesCompletionsnapshotsNewRoute
  '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdCompletionsnapshotsCompletionSnapshotIdIndexRoute
  '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/': typeof AuthenticatedCompaniesCompanyIdProjectsProjectIdInvoicesInvoiceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth/login'
    | '/'
    | '/companies/$companyId'
    | '/companies/$companyId/'
    | '/companies/$companyId/clients/new'
    | '/companies/$companyId/projects/new'
    | '/companies/$companyId/clients'
    | '/companies/$companyId/projects'
    | '/companies/$companyId/projects/$projectId'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/new'
    | '/companies/$companyId/projects/$projectId/invoices/new'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
    | '/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
    | '/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId'
    | '/companies/$companyId/projects/$projectId/invoices/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/companies/$companyId'
    | '/companies/$companyId/clients/new'
    | '/companies/$companyId/projects/new'
    | '/companies/$companyId/clients'
    | '/companies/$companyId/projects'
    | '/companies/$companyId/projects/$projectId'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/new'
    | '/companies/$companyId/projects/$projectId/invoices/new'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
    | '/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
    | '/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
    | '/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId'
    | '/companies/$companyId/projects/$projectId/invoices/$invoiceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/companies/$companyId/'
    | '/_authenticated/companies/$companyId/clients/new'
    | '/_authenticated/companies/$companyId/projects/new'
    | '/_authenticated/companies/$companyId/clients/'
    | '/_authenticated/companies/$companyId/projects/'
    | '/_authenticated/companies/$companyId/projects/$projectId/'
    | '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new'
    | '/_authenticated/companies/$companyId/projects/$projectId/invoices/new'
    | '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit'
    | '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update'
    | '/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new'
    | '/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/'
    | '/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/companies/$companyId"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/companies/$companyId": {
      "filePath": "_authenticated/companies/$companyId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/companies/$companyId/",
        "/_authenticated/companies/$companyId/clients/new",
        "/_authenticated/companies/$companyId/projects/new",
        "/_authenticated/companies/$companyId/clients/",
        "/_authenticated/companies/$companyId/projects/",
        "/_authenticated/companies/$companyId/projects/$projectId/",
        "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new",
        "/_authenticated/companies/$companyId/projects/$projectId/invoices/new",
        "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit",
        "/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update",
        "/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new",
        "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/",
        "/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/"
      ]
    },
    "/_authenticated/companies/$companyId/": {
      "filePath": "_authenticated/companies/$companyId/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/clients/new": {
      "filePath": "_authenticated/companies/$companyId/clients/new.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/new": {
      "filePath": "_authenticated/companies/$companyId/projects/new.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/clients/": {
      "filePath": "_authenticated/companies/$companyId/clients/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/": {
      "filePath": "_authenticated/companies/$companyId/projects/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/new.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/invoices/new": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/invoices/new.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/edit.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/update.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/invoices/completion_snapshots/new.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/completion_snapshots/$completionSnapshotId/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    },
    "/_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/": {
      "filePath": "_authenticated/companies/$companyId/projects/$projectId/invoices/$invoiceId/index.tsx",
      "parent": "/_authenticated/companies/$companyId"
    }
  }
}
ROUTE_MANIFEST_END */
