development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: fabati_development

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: fabati_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: fabati_production
