service: fabati-production

image: troptropcontent/fabati-production

servers:
  web:
    hosts:
      - 51.83.33.169
    proxy:
      ssl: true
      host: api.fabati.fr
  jobs:
    hosts:
      - 51.83.33.169
    cmd: bundle exec sidekiq

ssh:
  user: ubuntu

registry:
  username: troptropcontent
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - HEADLESS_BROWSER_TOKEN
    - DATABASE_URL
    - REDIS_URL
    - HEADLESS_BROWSER_WS
    - PRINT_MICROSERVICE_HOST
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - ACCESS_TOKEN_SECRET
    - REFRESH_TOKEN_SECRET
    - PRINT_TOKEN_SECRET
    - SENTRY_DSN

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  chromium:
    image: browserless/chrome:latest
    port: 9222:3000
    options:
      restart: unless-stopped
    env:
      secret:
        - HEADLESS_BROWSER_TOKEN
      clear:
        CONNECTION_TIMEOUT: "-1"
        DEFAULT_LAUNCH_ARGS: '["--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage"]'
    roles:
      - web
