# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - "sorbet/**/*"

RSpec:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/controllers/**/*"
    - "spec/services/**/*"

RSpec/VariableName:
  Exclude:
    - "spec/controllers/**/*"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/controllers/**/*"

RSpec/LetSetup:
  Exclude:
    - "spec/controllers/**/*"

RSpec/SharedContext:
  Exclude:
    - "spec/controllers/**/*"
RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 5

RSpec/ScatteredSetup:
  Exclude:
    - "spec/controllers/**/*"
