# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec

RSpec:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/VariableName:
  Exclude:
    - "spec/controllers/**/*"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/controllers/**/*"

RSpec/LetSetup:
  Exclude:
    - "spec/controllers/**/*"
